name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: show project file
        run: ls -la

      - name: checkout project
        uses: actions/checkout@v2

      - name: show project file
        run: ls -la
